[package]
name = "cpu_6502"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]
repository = "https://github.com/bgourlie/cpu6502"

[dev-dependencies]
asm6502 = {version = "^0.1.2"}
rand = "^0.5"
time = "^0.1"
